// _id: 5ca955aba33c4d0fa046a0c6 // 24 characters, generated by MongoDB driver -> see below

// 12 bytes, every 2 characters is a byte
    // first 4 bytes: timestamp // no need to create "CreatedAT", and can sort by ID to get time order
    // next 3 bytes: machine identifier
    // next 2 bytes: proccess identifer
    // next 3 bytes: counter byte


// 1 byte = 8 bits
// 2^8 = 256
// 256^3 = 16millions documents

// Same ID if:
// same time, same machine, same proccess and generate 15millions documents


// Mongoose -> MongoDB Driver -> MongoDB
// MongoDB is scalable because MongoDB doesn't generate an unique identifier by itself, can have several instances of mongodb
// Driver creates _id, almost unique


// generate custom ids:

const mongoose = require('mongoose');
const id = new mongoose.Types.ObjectId();
console.log(id)
console.log(id.getTimestamp())


const checkIfValidId = mongoose.Types.ObjectId.isValid('1234');

console.log(checkIfValidId)